---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "3.5-jdk-8-alpine"

inputs:
- name: source-code

outputs:
- name: package-output

run:
  path: source-code/ci/tasks/build-trading-engine.sh
